### ISSUE TITLE
Complete the instrumentation to verify that prov records are being collected

### ISSUE THREAD

**Issue by alanshaw** [libp2p/hydra-booster#15]

**Comment by daviddias** [comment]
Proposal, rather than having a special dedicated reported for the textui, go full Prometheus, use Prometheus metrics to populate the textui and track:

- Records stored in the shared datastore
- Number of unique PeerIds seen
- Total number of active connections
- Memory allocated
- Then per sybil
  - Sybil peerId
  - Sybil multiaddrs
  - Number of connections on that Sybil routing table

@alanshaw what do you think?

**Comment by alanshaw** [comment]
Sybil multiaddrs are not visible in Grafana (prometheus is not good for collecting this info) but they're available from the `/sybils` HTTP API.
