### ISSUE TITLE
Update Hydras to new HTTP Delegated Routing

### ISSUE THREAD

**Issue by BigLep** [libp2p/hydra-booster#180]
## Done Criteria
Hydras are using the HTTP Delegated Routing version compatible with https://github.com/ipfs/specs/pull/337 in production.

## Why Important
See motivation in https://github.com/ipfs/specs/pull/337 

## Notes
* Estimate in https://github.com/ipfs/go-delegated-routing/issues/63 was 2 developer days
* Tracking issue for this overall effort: https://github.com/ipfs/go-delegated-routing/issues/63.
   - Timeline coordination is happening there.
* There are multiple steps:
   - [ ] Add/merge client compatible with https://github.com/ipfs/specs/pull/337 (which includes removing the legacy Reframe client)
   - [ ] (After cid.contact deployment https://github.com/filecoin-project/storetheindex/issues/1038) Deploy new Hydra code with updated client

**Comment by guseggert** [comment]
Main code change in https://github.com/libp2p/hydra-booster/commit/8be14bf61bff477319273e5757da95c382c01a73

I have also turned off OpenSSL in the Docker build since it keeps causing problems, it's now using Go's crypto.  I'll monitor perf around that.

I've deployed this to the test instance, see https://github.com/libp2p/hydra-booster-infra/pull/14

I'll let it bake overnight, if everything looks good tomorrow then I'll deploy to the whole fleet.

**Comment by BigLep** [comment]
Hi @guseggert .  Did the prod deployment happen?  Are there client side (Hydra) and server-side (cid.contact) graphs you're monitoring?

**Comment by BigLep** [comment]
@guseggert : how is this looking?

Also, please share the issue with go-libp2p when you have it.

**Comment by guseggert** [comment]
I was able to grab another profile showing the OpenCensus tag allocations from OpenCensus, opened an issue with go-libp2p here: https://github.com/libp2p/go-libp2p/issues/1955

I've been fighting with resource manager and I have given up on it and turned it off, and things are looking better now. Every time I would fix one limit, another would pop up and cause some degenerate behavior somewhere else, and chasing down the root cause of throttles is non-trivial. We need to move forward here so I am just disabling resource manager for now.

**Comment by BigLep** [comment]
@guseggert : can you also point to how you were configuring the resource manager?  (I'm asking so can learn what pain another integrate experienced.)  I would have expected us toonly have limits like Kubo's strategy.

**Comment by guseggert** [comment]
Each hydra host is effectively running many Kubo nodes at the same time, and they also don't handle Bitswap traffic, so the traffic pattern is pretty different from a single Kubo node. 

The RM config currently deployed to prod hydras is here: https://github.com/libp2p/hydra-booster/blob/master/head/head.go#L82 . Note that those are per-head limits. After upgrading from go-libp2p v0.21 to v0.24, there was significantly more throttling, so I've been tweaking them locally and [in a branch](https://github.com/libp2p/hydra-booster/commits/feat/no-rcmgr-obs-no-openssl-no-reframe). As part of that, I pulled resource manager and connection manager out to be shared across heads instead, which makes reasoning about limits easier. Connmgr is also involved since it prunes connections and forces re-connects, causing periodic spikes in new conns (forcing you to care about conn limits, identify limits, etc.). When RM throttling was interfering, there was much less processed reqs by the DHT but much higher mem usage and goroutines, mostly stuck on the identify handshake...I didn't trace through the code but I'm suspecting that they were somehow stuck due to RM throttling.

**Comment by guseggert** [comment]
Coordinated with @masih this morning to flip the full Hydra fleet over to the HTTP API.  Things are looking fine. The p50 cid.contact latency has dropped from ~36 ms to ~18 ms.

**Comment by BigLep** [comment]
Resolving since done criteria is satisfied.
